export const ADD_TO_ORDER = "ADD_TO_ORDER";
export const ADD_TO_ORDER_FAIL = "ADD_TO_ORDER_FAIL";
export const REMOVE_FROM_ORDER = "REMOVE_FROM_ORDER";
export const REMOVE_FROM_ORDER_FAIL = "REMOVE_FROM_ORDER_FAIL";
export const ADD_TO_ORDER_RESET = "ADD_TO_ORDER_RESET";